name: Ubuntu install test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 6 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    defaults:
      run:
        shell: bash -l {0}
    name: xsarsea with python ${{ matrix.python-version }} on Ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda and create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: xsarsea
          python-version: ${{ matrix.python-version }}
      - name: Install xsarsea dependencies
        run: conda install -c conda-forge pytest
      - name: Install xsarsea
        run: |
          pip install -e .
          pip install -r requirements.txt
      - name: Check xsarsea environment
        run: |
          conda info
          python -V
      - name: Testing xsarsea
        run: pytest

